# Generated by Django 3.1.5 on 2021-02-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
