# Generated by Django 3.1.5 on 2021-03-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.CharField(max_length=50)),
                ('song', models.CharField(blank=True, max_length=100, null=True)),
                ('data_type', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
